<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
    <RootNamespace>Assign_2</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 <ItemGroup>
   <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
   <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
 </ItemGroup>

</Project>
